#pragma once
#define RESOURCE_SHELL_INPUT_SIZE 512
#define RESOURCE_SHELL_OUTPUT_SIZE 2048
#define RESOURCE_SHELL_MAX_ARGS 10
#define RESOURCE_SHELL_COMMAND_HISTORY_LENGTH 1
#define RESOURCE_SHELL_TEMP_ARRAY_SIZE 1024
#define RESOURCE_SHELL_ENABLE_HELP 